// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhfv7350oX_PmMlO5DxNBvaidstbV9P_4',
    appId: '1:199731539549:web:0eccb20c94824cec98a7b4',
    messagingSenderId: '199731539549',
    projectId: 'fluxchat-18d56',
    authDomain: 'fluxchat-18d56.firebaseapp.com',
    storageBucket: 'fluxchat-18d56.firebasestorage.app',
    measurementId: 'G-BG99BMJ9FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEAclBDU-F8EMkw5DpP4WDSVz9FL7rMC0',
    appId: '1:199731539549:android:8446a3c2ab0507d098a7b4',
    messagingSenderId: '199731539549',
    projectId: 'fluxchat-18d56',
    storageBucket: 'fluxchat-18d56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXA0qFO4fwMfZQEnm4TKvrb1kWRJgDVMY',
    appId: '1:199731539549:ios:7b0733cbfcdb2a6498a7b4',
    messagingSenderId: '199731539549',
    projectId: 'fluxchat-18d56',
    storageBucket: 'fluxchat-18d56.firebasestorage.app',
    iosBundleId: 'com.example.fluxchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXA0qFO4fwMfZQEnm4TKvrb1kWRJgDVMY',
    appId: '1:199731539549:ios:7b0733cbfcdb2a6498a7b4',
    messagingSenderId: '199731539549',
    projectId: 'fluxchat-18d56',
    storageBucket: 'fluxchat-18d56.firebasestorage.app',
    iosBundleId: 'com.example.fluxchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhfv7350oX_PmMlO5DxNBvaidstbV9P_4',
    appId: '1:199731539549:web:3298046705a9ac2198a7b4',
    messagingSenderId: '199731539549',
    projectId: 'fluxchat-18d56',
    authDomain: 'fluxchat-18d56.firebaseapp.com',
    storageBucket: 'fluxchat-18d56.firebasestorage.app',
    measurementId: 'G-E653EHGJD2',
  );
}
